id: I35175E57
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:31:53+00:00'
last_modified: '2022-06-08T01:58:13.684318+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20463
  title: རྟོགས་གཞིགས་གསར་པའི་འདུ་ཤེས་ཀྱི་ཡོ་ལང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '4706':
      image_group_id: I1KG12350
      title: ''
      total_pages: 354
      order: 1
      base_file: 4706.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
