id: P004564
initial_creation_type: ocr
source_metadata:
  id: bdr:W20463
  title: རྟོགས་གཞིགས་གསར་པའི་འདུ་ཤེས་ཀྱི་ཡོ་ལང་།
  author: ''
  volumes:
    5e08e4df0a88412d9ba80daaf7350e74:
      image_group_id: I1KG12350
      title: ''
      volume_number: 1
      total_pages: 354
      base_file: v001.txt
