id: P004564
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:41:55.790410
source_metadata:
  id: bdr:W20463
  title: རྟོགས་གཞིགས་གསར་པའི་འདུ་ཤེས་ཀྱི་ཡོ་ལང་།
  author: ''
  volumes:
    5e08e4df0a88412d9ba80daaf7350e74:
      image_group_id: I1KG12350
      title: ''
      volume_number: 1
      total_pages: 354
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
